### ISSUE TITLE
still asks me to allow networks but i have and its still asking? any answers?

### ISSUE THREAD

**Issue by THEVIRUS-g** [Lakatrazz/Fusion-Helper#10]
![Screenshot 2023-09-04 131401](https://github.com/Lakatrazz/Fusion-Helper/assets/144002767/7db6f3c0-4052-4a7e-84a5-6b6c38bf4e17)
sooooo yeah I gave it permission to both networks and it still say the following: Be sure to allow FusionHelper access both public and private networks if/when the firewall asks. and i cant get the command to run @Lakatrazz can you help me pleas !!!

**Comment by yanistefan** [comment]
make sure your quest and pc are on the same wifi and try ingnoring the error and booting up bonelab on quest anyways (with steam running in the bg)

**Comment by 1647813** [comment]
im having the same problem I've tried everything need HELP!!!

**Comment by yanistefan** [comment]
That line of text is always going to be there, as far as I'm aware. Even while fusion is running the text is still there so I would recommend ignoring it. I don't want to have to repeat stuff I've already said so if you have further issues then I would recommend checking out the other support forum made on loosely the same subject by tombstonesoda

**Comment by Lakatrazz** [comment]
Stale

**Comment by ccgdfn** [comment]
its not asking to me to enable pravite and public server in bonelab please fix firewall to ask us
