### ISSUE TITLE
Apk plz?

### ISSUE THREAD

**Issue by Henrrymm6824** [Lakatrazz/Fusion-Helper#13]
Apk of this so i can do it on android?

**Comment by StarBubbel** [comment]
you can try to do it trough termux using ubuntu and steam but other then that they did not make a apk because steam networking does not work on the steam mobile app.

**Comment by Henrrymm6824** [comment]
No I can run bonelab on my phone i can download exe and run exe files I downloaded lemon installer to

**Comment by Lakatrazz** [comment]
Not how it works
