### ISSUE TITLE
some reason wont work nor connect to my head set

### ISSUE THREAD

**Issue by BreadyUwU** [Lakatrazz/Fusion-Helper#14]
i have followed minibattle lops's tutorial bit by bit and still wont connect to my head set i keep on getting this message even when i gave access to both private and public
![image](https://github.com/Lakatrazz/Fusion-Helper/assets/117021667/da5ee726-1bee-432b-8184-338f76dc9126)
it says client connected but on my headset it says to connect

**Comment by BreadyUwU** [comment]
so i tried using my phones hotspot
![image](https://github.com/Lakatrazz/Fusion-Helper/assets/117021667/389a1912-467e-4c82-842b-2455eeee3dc5)

**Comment by CJendantix** [comment]
This uses a LAN connection. LAN meaning Local Access Network, in laymen's terms, devices that are connected to the same WiFi network can communicate directly. Windows devices have a built-in firewall to stop unwanted, and sometimes malicious connections between devices. When this program starts, Windows should automatically pop up with a window that asks you if you want to allow this connection. You have to allow it on both public and private networks for this program to function properly. Assuming you did this correctly, the program uses Steam's servers to facilitate multiplayer over the internet, so you need to have Steam installed and be logged in.

**Comment by wildryry** [comment]
I've done everything you've said and the issue still remains also i got it working before but now it won't connect and I don't have a clue as to why

**Comment by The0wh0watches** [comment]
> I've done everything you've said and the issue still remains also i got it working before but now it won't connect and I don't have

I have this same issue right now, anyone know a fix?

**Comment by Lakatrazz** [comment]
Stale
