### ISSUE TITLE
Win Arm

### ISSUE THREAD

**Issue by jamersb** [Lakatrazz/Fusion-Helper#15]
Hi,

Just wondering if anyone knows why this is happening?
I'm watching a tut rn and it says to download FusionHelper_win_armx64.zip, but that isnt there, the only one that is there is FusionHelper_win_x64.zip, not the one I need
![win arm ](https://github.com/Lakatrazz/Fusion-Helper/assets/144098130/3d185d68-4518-47ea-aa6b-c46af0fd2799)

**Comment by StarBubbel** [comment]
only time you really need to use arm64 is when your computer is running on arm64 but most computers are x64 only time you use a arm64 processor is on a phone.

**Comment by Lakatrazz** [comment]
Stale
