### ISSUE TITLE
Firewall encountered issues.

### ISSUE THREAD

**Issue by TogenMamagen** [Lakatrazz/Fusion-Helper#16]
Firewall doesnt pop up when first starting the app.

Some computers block the app from accessing both private and public networks, maybe find a way to fix it so that doesnt happen?(or override it)
![image_2023-09-05_120646786](https://github.com/Lakatrazz/Fusion-Helper/assets/144147418/3e3fdcda-5d42-46d0-8f0c-6619f53c61b3)

Only the win version of the app works on my machine and win arm doesnt start up even tho steam is set up and the lap top or computer has windows 10 & 11. (and has net 6.0)
![image_2023-09-05_113446752](https://github.com/Lakatrazz/Fusion-Helper/assets/144147418/39ccb455-4cfb-4ec1-8bde-d7ab25aefa03)

(fixed: Go to properties on the app and go to general, you will see a option to unblock the app. tick it then press apply.)
Some lap tops like school lap tops block you from even running the app bc of unknown publishers, and take out the run anyway button. (making me and possibly others unable to run the application on both win and win_arm)
![image_2023-09-05_111611229](https://github.com/Lakatrazz/Fusion-Helper/assets/144147418/7746688d-901c-4e9a-90fe-6f09b7abc821)

**Comment by StarBubbel** [comment]
Win arm wont work because it is meant for computers that run on arm64 processors and what you can do to make the firewall work is turn it off for private networks. Then make the network your on a private network. Unless you have a virus on your computer opening up your firewall wont really do anything bad. I cant really do anything about the school laptops as you are not supposed to be running that on your school devices.

**Comment by TogenMamagen** [comment]
> Win arm wont work because it is meant for computers that run on arm64 processors and what you can do to make the firewall work is turn it off for private networks. Then make the network your on a private network. Unless you have a virus on your computer opening up your firewall wont really do anything bad. I cant really do anything about the school laptops as you are not supposed to be running that on your school devices.

actually technicaly you can after factory resetting the device, it works for a bit but then gets blocked. and i tried turning it off for the time being to see if it would work but nah, but yeah you can run it on a school lap top, we just need to find a way to stop the sistem from blocking the app.

**Comment by Lakatrazz** [comment]
Stale
