### ISSUE TITLE
ファイヤーウォールが認識しません

### ISSUE THREAD

**Issue by yuyop123** [Lakatrazz/Fusion-Helper#17]
Windows11 が悪いのか　マカフィーが悪いのか　日本では使用できないのか分かりません　フルバージョンのwin×64です

**Comment by yuyop123** [comment]
https://github.com/Lakatrazz/Fusion-Helper/assets/144211544/46871cf3-f0d9-48d8-9b1a-c070b1b80a8e

![2023-09-06_16h23_42](https://github.com/Lakatrazz/Fusion-Helper/assets/144211544/3b545e4c-ded3-4a06-aa3b-f882791d3a92)

**Comment by yuyop123** [comment]
ファイヤーウォールを許可しましたがここから動きません
どれがダメなのか全くわかりません

**Comment by yuyop123** [comment]
クエストにそうしんしましたが認識されませんでした
マカフィーが原因なのか
Windows11が原因なのか
そもそも日本に対応してないのか分かりませでした
あとUSBはとっていいのですか

**Comment by CJendantix** [comment]
正直、よくわかりませんが、steamサーバーを使用しているので日本でも使えると思います。一般に、McAfee は悪質なため、このような望ましくない可能性のあるプログラムには近づかないようにする必要があります。最近では、Windows に組み込まれているウイルス対策機能が十分に機能します。

**Comment by yuyop123** [comment]
quest2に
認識されましたがフュージョンヘルパーのプロントがこのへんで止まっています
ファイヤーウォールを許可しましたが
![2023-09-06_21h14_15](https://github.com/Lakatrazz/Fusion-Helper/assets/144211544/d936fac3-a161-495d-9ffd-82c29f74e0a6)
ここからびくともしないです
[youtubeのフュージョンヘルパーチュートリアルだとWindows10なので(Windows11フュージョンヘルパーチュートリアルの見つからないので)])
Windows11と互換性ないでしょうかフュージョンヘルパー
またはマカフィーをアンインストールでしょうか
もしWindows11フュージョンヘルパーチュートリアルがあったらリンクよろしくお願いいたします。

**Comment by yuyop123** [comment]
(Google通訳がバグってるので元の言語で使用よろしくお願いいたします。)

**Comment by yuyop123** [comment]
使えましたありがとうございました
