### ISSUE TITLE
起動しましたがどうやってマルチプレイヤーできますか

### ISSUE THREAD

**Issue by yuyop123** [Lakatrazz/Fusion-Helper#18]
どうすればできますか

**Comment by CJendantix** [comment]
ヘッドセットに Fusion がインストールされていますか?

**Comment by yuyop123** [comment]
インストールされてますが
USB外しても大丈夫ですか私のFusionヘルパーはUSBと繋がっていますUSBなしで繋がらりますか
Youtubeのチュートリアルではそのあとが書かれていません

**Comment by yuyop123** [comment]
Fusionのメニューが表示されません
