### ISSUE TITLE
Not Opening on macOS 12.6.3

### ISSUE THREAD

**Issue by mrbreast3** [Lakatrazz/Fusion-Helper#19]
It says for some reason "This application "FusionHelper" can't be opened." I don't know why but does anyone have an idea why?

**Comment by CJendantix** [comment]
How are you running it? This is a command-based program, it cannot be run by double-clicking the file in Finder.

**Comment by mrbreast3** [comment]
I was using the Finder File, How can I run it from the command line?Deez Nuts
***@***.***
 

    On Wednesday, September 6, 2023 at 07:26:35 PM EDT, CJendantix ***@***.***> wrote:  
 
 


How are you running it? This is a command-based program, it cannot be run by double-clicking the file in Finder.

**Comment by MisterMe510** [comment]
> It says for some reason "This application "FusionHelper" can't be opened." I don't know why but does anyone have an idea why?

What I had to do to open it was right click on it and click open.

**Comment by Lakatrazz** [comment]
Stale
