### ISSUE TITLE
SteamOS (Arch) x86 linux. fusion helper "bind exeption"

### ISSUE THREAD

**Issue by LhymeFruit** [Lakatrazz/Fusion-Helper#21]
console outputs:
```
[B]Bind exception: System.Net.Sockets.SocketException (98): Address already in use
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at LiteNetLib.NetManager.BindSocket(Socket socket, IPEndPoint ep), errorCode: AddressAlreadyInUse
Initialized UDP socket on port 0

```
Fusionhelper has the required firewall permissions 
ive tried running sudo, ive tried disabling the read only rootfs
nothing has worked.
Im not sure if there is a dependency im not told about or nothing
steam is open and steamvr is in my library

**Comment by LhymeFruit** [comment]
the issue was fixed by installing microsoft .net for linux. This should be in the readme and not hidden in the files for someone to find.

**Comment by deathkiller55** [comment]
Just wondering how did you got .net on the steam deck?

**Comment by LhymeFruit** [comment]
> Just wondering how did you got .net on the steam deck?

digging through the files there is an SH file to install .net linux just make sure to use "sudo steamos-readonly disable" before running it. after run "sudo steamos-readonly enable".

**Comment by deathkiller55** [comment]
> > Just wondering how did you got .net on the steam deck?
> 
> digging through the files there is an SH file to install .net linux just make sure to use "sudo steamos-readonly disable" before running it. after run "sudo steamos-readonly enable".

Can't seem to find the SH file but thanks for the help

**Comment by Lakatrazz** [comment]
Person fixed issue
