### ISSUE TITLE
Fusion helper not starting

### ISSUE THREAD

**Issue by Mrbirdman420** [Lakatrazz/Fusion-Helper#22]
Everytime i try to run Fusion helper on my pc it does not load
When i do press run it appears for 1 second then it closes is there anyway i can fix this or?

**Comment by Adadeane** [comment]
Hello, This would mean you don't have .net 6.0 you can download it here: https://dotnet.microsoft.com/en-us/download/dotnet/6.0

**Comment by KatNPant** [comment]
I have that and i have the same problem

**Comment by Adadeane** [comment]
Check an online tutorial and make sure you do everything exactly the same.

**Comment by Lakatrazz** [comment]
Stale
