### ISSUE TITLE
Firewall Not Popping Up 

### ISSUE THREAD

**Issue by Shxdowxdizzy** [Lakatrazz/Fusion-Helper#24]
Everytime i Open The FusionHelper It keeps Saying "Alow FusionHelper Access Both Public And Private Netwrorks If/When The Firewall Asks' But The Firewall Never Pops Up It Very Fustrating:(

**Comment by TarqS2** [comment]
Yeah i also dont know how to fix that

**Comment by Lakatrazz** [comment]
Stale
