### ISSUE TITLE
Something isn’t working

### ISSUE THREAD

**Issue by gorrilaboi69** [Lakatrazz/Fusion-Helper#26]
Idk what’s happening I patched bonelab and put all the files where they need to be but the helper always stops at this
![IMG_7487](https://github.com/Lakatrazz/Fusion-Helper/assets/100235396/53cc823f-7656-4ce5-bb06-980548832f27)

**Comment by sasdallas** [comment]
Fixed by switching to public beta - you can do this in the Oculus App.

**Comment by Lakatrazz** [comment]
Stale
