### ISSUE TITLE
MacOS Fusion Helper not connecting

### ISSUE THREAD

**Issue by MisterMe510** [Lakatrazz/Fusion-Helper#28]
Im using a MacOS to mod my quest and I used this tutorial to do it. https://www.youtube.com/watch?v=rqRH6twupDU&t=126s&ab_channel=MinibattleLop (When they clicked windows I just used MacOS)
Everything worked fine until i tried going online. When I launch the application the firewall pops up and I click allow and It says "Client has found server, letting it know" which I assume means it worked. Then when I go onto my quest and try to join or create any server it tells me to check if fusion helper is running. My quest IS still connected to my computer and I can't see what I'm doing wrong. Also I do have Steam and Sidequest running. Can anyone help?

**Comment by Lakatrazz** [comment]
Stale
