### ISSUE TITLE
issues on zorion os

### ISSUE THREAD

**Issue by Spinninluigi** [Lakatrazz/Fusion-Helper#30]
I tried running it and got the terminal up, but it connects and immediatly wants to close, any helps?

**Comment by Jajoo2** [comment]
Maybe try running it directly from the terminal? if you're already doing that, then i don't know.

**Comment by loganharber** [comment]
you need you extract the folder and then open it in the folder and dont use shortcuts or wont open

**Comment by Lakatrazz** [comment]
Stale
