### ISSUE TITLE
Wont Start up or work. :(

### ISSUE THREAD

**Issue by randompersonwithanissue** [Lakatrazz/Fusion-Helper#34]
conditions = I have .NET on the latest version and I've uninstalled and reinstalled 30 times I've run it as administration and everything I have Windows 64x.
when I open it it instantly closes and when I spammed it open it opened but didn't run. I've been trying for the past 3 months to get it fixed... It worked the first time I tried it for about a week then it stopped having permission, so I uninstalled and reinstalled it and now it won't open. someone, please help. Also when I try to open it in the file explore it won't open and makes me run it from my desktop. 
The firewall thing showed up once I did what Minibattlelop said to do and it worked but it doesn't show up now... (no idea if its a cause)

**Comment by randompersonwithanissue** [comment]
it literally won't turn on...
I've tried 7 times again, I open the game I try to load the servers, and Fusion Helper is frozen because it won't open or start at ALL. and the game asks me to run Fusion Helper...

**Comment by randompersonwithanissue** [comment]
If Lakatrazz sees this I just want to say I hope Fusion gets put in the main game in the update or in the future just in the mod manager or something. but anyway if it's not added anytime soon I wish you the best it's most likely my PC being doo doo.

**Comment by loganharber** [comment]
you need you extract the folder and then open it in the folder and dont use shortcuts or wont open

**Comment by DanielV69** [comment]
cool, man

**Comment by Lakatrazz** [comment]
Stale
