### ISSUE TITLE
FusionHelper not running properly

### ISSUE THREAD

**Issue by RandomCakes** [Lakatrazz/Fusion-Helper#4]
When I open it this happens

![image](https://github.com/Lakatrazz/Fusion-Helper/assets/109817877/cb7b3f62-a258-4018-8516-5e92cb2958d7)

If anyone can help that would be amazing

**Comment by RandomCakes** [comment]
my fault realized it wasnt an issue

**Comment by The0wh0watches** [comment]
> my fault realized it wasnt an issue

What did you do to fix it? I have this same issue
