### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Ineedhelplzth** [Lakatrazz/Fusion-Helper#44]
fusion helper open up just fine and it shows steam is open but when I go in to bonelab on quest I can’t log in and I keep pressing the login button and nothing happens  and in fusion helper it says quest not connected and I am using a Chromebook so could that be a problem

**Comment by Lakatrazz** [comment]
Chromebook is not guaranteed to work

**Comment by Ineedhelplzth** [comment]
Ok thx

**Comment by Ineedhelplzth** [comment]
Ok thx
