### ISSUE TITLE
Problems with server

### ISSUE THREAD

**Issue by CharlieRedPants123** [Lakatrazz/Fusion-Helper#46]
Hello! I am reaching out for some help with the fusion helper using macOS  13.7.1.
I have launched bonelab and have connected my steam acc. The helpers says i am connected using my port and my quest was picked up by the program. For some unknown reason i have zero access to any of the servers and or games open. All of the mods I need have been installed.  Also there has been no firewall pop up asking to receive information.

If you can help with this issue it would be much appreciated. Thanks! Merry Christmas!

**Comment by Lakatrazz** [comment]
Please follow the instructions here: https://github.com/Lakatrazz/BONELAB-Fusion/wiki/Common-Fixes#i-cant-make-serversit-says-no-servers-found-macos-fusionhelper

**Comment by CharlieRedPants123** [comment]
It works now! Thank you lakatrazz!
