### ISSUE TITLE
Just wondering

### ISSUE THREAD

**Issue by FattywithPower** [Lakatrazz/Fusion-Helper#5]
Do I need to put the .dll file into my bonelab mod or plugin folder? just curious. Also my fusion keeps telling me to allow access through to the networks but the prompt never pops up.

**Comment by EspressoBlitz** [comment]
wild, same. shared problem I guess

**Comment by Lakatrazz** [comment]
LabFusion.dll goes in the mods folder, on quest you can ignore the LabFusionUpdater.dll. If the prompt never appears, manually go to your firewall and give FusionHelper permission (search "Allow an app through windows firewall" in your search bar).
