### ISSUE TITLE
API Not Loading

### ISSUE THREAD

**Issue by The0wh0watches** [Lakatrazz/Fusion-Helper#6]
FusionHelper keeps saying "API Loaded No" after it says its caching my SteamID when I try to connect with my quest 2. Please, does anyone know how to fix this?

This is what it says exactly:

Initializing Steamworks with appid [BLANK]
Setting breakpad minidump AppID = [BLANK]
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  [BLANK] [API loaded no]

**Comment by Lakatrazz** [comment]
API loaded no is what it normally says, you're fine.

**Comment by The0wh0watches** [comment]
> API loaded no is what it normally says, you're fine.
Every time I load into BL, I don't see all the different machines showing up in the main menu showing that fusion is installed correctly. I just bought the game today and finished the beginning level and only just loaded into the BL Hub, is there something else I need to do?
