### ISSUE TITLE
no firewall prompt

### ISSUE THREAD

**Issue by tombstonesoda** [Lakatrazz/Fusion-Helper#8]
when i run the exe there is no firewall prompt and it does not make it past the firewall message
![Screenshot 2023-09-03 191631](https://github.com/Lakatrazz/Fusion-Helper/assets/99777069/0c4a4aff-d422-4741-9ce8-fab18dc80f17)

**Comment by tombstonesoda** [comment]
i opened my firewall and allowed the app to pass through both private and public networks manually and its still not working.

**Comment by yanistefan** [comment]
having same issue, will try to report if i find the error

**Comment by yanistefan** [comment]
wait, think i might have found something, idk im not good with computers, watch minibattle lop's tutorial on bonelab fusion and go to 9:43 notice anything weird?

**Comment by tombstonesoda** [comment]
i have tried arm but it just tells me that i cannot run the app at all and to get a different one
![Screenshot 2023-09-03 194650](https://github.com/Lakatrazz/Fusion-Helper/assets/99777069/fec2ad26-b428-4353-9808-dbbaab0d7c46)

**Comment by yanistefan** [comment]
yea same, only thing i can guess is going on here is that theres something wrong with the normal windows 64 version,since there should be no other explanation since the other versions work for other people,altough im sure a fix will come soon and im kinda not in the mood to look through hundreds of files for hours on end tonight.

**Comment by THEVIRUS-g** [comment]
hi i have the same problem Lakatrazz will you fix?

**Comment by THEVIRUS-g** [comment]
@Lakatrazz please fix this i need fusion pleaseeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee i just ate a whole water melon slice in one bite now i have suvere belly aches

**Comment by yanistefan** [comment]
> i opened my firewall and allowed the app to pass through both private and public networks manually and its still not working.
make sure your quest and pc are on the same wifi and try ingnoring the error and booting up bonelab on quest anyways (with steam running in the bg)

**Comment by yanistefan** [comment]
> > wait, think i might have found something, idk im not good with computers, watch minibattle lop's tutorial on bonelab fusion (quest) and go to 9:43 notice anything weird?
> > never mind its because he uses arm64 instead of regular, but why does arm64 works just fine but regular 64 doesn't?
> 
> I don't know what's going wrong here, but to try and hopefully point someone in the right direction, I do NOT use Arm64. I use win_64. It works no issue on all 3 PC's I've tested so far.

i think i may have found the solution to the problem. but now im curious why yours only has a handful of files while when i download the zip there are hundreds of them

**Comment by tombstonesoda** [comment]
![image](https://github.com/Lakatrazz/Fusion-Helper/assets/99777069/bf6f3311-1435-4bdf-8791-b624a6bec086)
the unzipped windows 64 folder has 230 files most being application extensions i have used both windows and 7zip to extract them and their both the same

**Comment by KayKilla426** [comment]
i roughly the same problem, basically i had ran FusionHelper perfectly fine and had gotten the prompt but i had accidentally closed it out and now when i open FusionHelper it wont give the prompt.

**Comment by Minibattle** [comment]
> 

That is because I am using an older build. I currently use the release build of everything and it all works the same.

**Comment by Ranger174** [comment]
I am having the same problem and I have looked at three tutorials but nothing on this topic I am dyeing to play fusion.

**Comment by Minibattle** [comment]
> I am having the same problem and I have looked at three tutorials but nothing on this topic I am dyeing to play fusion.

out of curiosity, could you try running Fusion Helper as administrator and seeing if that fixes it?

**Comment by Boshidvagyok** [comment]
hi i followed minibattles tutorial and it doast work im really sad did i do something wrong? the firewwall thingie doasnt show up pls help me.

**Comment by yanistefan** [comment]
Try checking firewall in windows settings (it should open another app called windows security) then press "allow an app through the firewall" and find fusion on the list of apps, check both boxes and press ok. then try running bonelab of course while running fusionhelper and steam and all that. 

hope this helps

**Comment by Ranger174** [comment]
I will try this

**Comment by Ranger174** [comment]
I have allowed it but it still is how it is when first booted up

**Comment by yanistefan** [comment]
> I have allowed it but it still is how it is when first booted up

what do you mean by the same?

**Comment by Ranger174** [comment]
Like when you dont allow it

**Comment by Ranger174** [comment]
I am trying as hard as I can to make this work

**Comment by yanistefan** [comment]
> Like when you dont allow it

idk what thats meant to look like if you mean the text at the top of fusionhelper, at least for me thats always been there even while in fusion so i would reccomend you ignore it, altough if you mean something else then i would reccomend finding someone else as the only reason mine works is a combination of doing random stuff and pure luck

**Comment by Ranger174** [comment]
Ok im going on my headset to see if it works

**Comment by Ranger174** [comment]
Does public lobbies work?

**Comment by Ranger174** [comment]
Or do i need to join someone with a Steam ID

**Comment by yanistefan** [comment]
> Does public lobbies work?

idk ,i could try rn

**Comment by Ranger174** [comment]
Ok if it works then i did it wrong

**Comment by yanistefan** [comment]
mine appears to be working just fine, any error message or.. like what went wrong?

**Comment by Ranger174** [comment]
Well it says connection timed out when i refresh to search for lobbies

**Comment by yanistefan** [comment]
> Well it says connection timed out when i refresh to search for lobbies

do you have both steam and the helper running on a pc/laptop with the same wifi?

**Comment by Ranger174** [comment]
> > Well it says connection timed out when i refresh to search for lobbies
> 
> do you have both steam and the helper running on a pc/laptop with the same wifi?

Yeah

**Comment by Ranger174** [comment]
I DID IT!!!!!!!!!

**Comment by Ranger174** [comment]
Thanks for the help

**Comment by yanistefan** [comment]
> I DID IT!!!!!!!!!

congrats what was the fix?

**Comment by Ranger174** [comment]
Ok if you want to fix this (Im not going in detail) you need to use the "Allow an app through the firewall" setting once you figure that out you then need to see if you are doing the private network option on the wi-fi and thats how i did it

**Comment by Ranger174** [comment]
> Ok if you want to fix this (Im not going in detail) you need to use the "Allow an app through the firewall" setting once you figure that out you then need to see if you are doing the private network option on the wi-fi and thats how i did it

Hope this Helps!

**Comment by TarqS2** [comment]
> Minibattle

Yo im trying to do that but it wont let me it says its got public network but i cant mess with anything on it for some reason and im  getting really annoyed about it i cant figure it out

**Comment by TarqS2** [comment]
@Ranger174

> > Ok if you want to fix this (Im not going in detail) you need to use the "Allow an app through the firewall" setting once you figure that out you then need to see if you are doing the private network option on the wi-fi and thats how i did it
> 
> Hope this Helps!

I need help on setting it up as i read comments tried and failed it still says the same thing.

**Comment by EthanRomine** [comment]
If you have your firewall turned off that might be why. Also here is the fix that worked for me:

**Comment by Lakatrazz** [comment]
Stale
